apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-rb
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
