apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: carol
  namespace: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pods-read
subjects:
- kind: ServiceAccount
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
