apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    role: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: nginx # Название контейнера
      image: flying1900/websrv:1.0.1 # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:latest
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
